[2024-12-01T02:09:15.398+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_order.create_postgres_conn manual__2024-12-01T02:09:12.113908+00:00 [queued]>
[2024-12-01T02:09:15.413+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_order.create_postgres_conn manual__2024-12-01T02:09:12.113908+00:00 [queued]>
[2024-12-01T02:09:15.413+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-01T02:09:15.442+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_postgres_conn> on 2024-12-01 02:09:12.113908+00:00
[2024-12-01T02:09:15.459+0000] {standard_task_runner.py:60} INFO - Started process 498 to run task
[2024-12-01T02:09:15.464+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'init_order', 'create_postgres_conn', 'manual__2024-12-01T02:09:12.113908+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/init_order.py', '--cfg-path', '/tmp/tmp0ydo4y3c']
[2024-12-01T02:09:15.479+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask create_postgres_conn
[2024-12-01T02:09:15.508+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-01T02:09:15.603+0000] {task_command.py:423} INFO - Running <TaskInstance: init_order.create_postgres_conn manual__2024-12-01T02:09:12.113908+00:00 [running]> on host d047790ecdd5
[2024-12-01T02:09:15.801+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_order' AIRFLOW_CTX_TASK_ID='create_postgres_conn' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T02:09:12.113908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T02:09:12.113908+00:00'
[2024-12-01T02:09:15.803+0000] {logging_mixin.py:188} INFO - Session created
[2024-12-01T02:09:15.804+0000] {logging_mixin.py:188} INFO - Connections listed
[2024-12-01T02:09:15.820+0000] {logging_mixin.py:188} INFO - Connection already exists
[2024-12-01T02:09:15.820+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-01T02:09:15.842+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=init_order, task_id=create_postgres_conn, execution_date=20241201T020912, start_date=20241201T020915, end_date=20241201T020915
[2024-12-01T02:09:15.917+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-01T02:09:15.977+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
